@Api_HostAddress = http://localhost:5000

### Start a search
POST {{Api_HostAddress}}/api/books/search?query=tolkier+hobbit+illustrated+1937
Accept: application/json

### Connect to the sso channel and wait for the result
GET {{Api_HostAddress}}/api/books/stream/8a412276-c462-499a-a35c-4583db1a528a
Accept: text/event-stream